import { BlogStatus } from '@/pages/cms/blogs/types/blog.types';
import blogGoldImage from '@/assets/images/blog-gold.jpg';

export const blogsList = [
  {
    id: 1,
    status: BlogStatus.PUBLISHED,
    title: 'Guide to Gold Investment',
    description: 'Start your journey with gold and learn how to invest safely with small amounts.',
    image: blogGoldImage,
    date: '19 Apr 2026',
    readingTime: 3,
    publishedDate: '18 Apr 2026',
  },
  {
    id: 2,
    status: BlogStatus.DRAFT,
    title: 'How to Ace Your Next Karat Interview',
    description: 'Practical tips and real-world strategies to help you pass technical interviews.',
    image: blogGoldImage,
    date: '15 Apr 2026',
    readingTime: 5,
    publishedDate: '18 Apr 2026',
  },
  {
    id: 3,
    status: BlogStatus.DRAFT,
    title: 'Top 10 Coding Interview Questions',
    description: 'A curated list of the most commonly asked coding questions in tech interviews.',
    image: blogGoldImage,
    date: '10 Apr 2026',
    readingTime: 7,
    publishedDate: '18 Apr 2026',
  },
  {
    id: 4,
    status: BlogStatus.PUBLISHED,
    title: 'How to Prepare for a System Design Interview',
    description:
      'Deep-dive into system design concepts you need to know before your big interview.',
    image: blogGoldImage,
    date: '05 Apr 2026',
    readingTime: 10,
    publishedDate: '04 Apr 2026',
  },
  {
    id: 5,
    status: BlogStatus.DRAFT,
    title: 'The Future of Artificial Intelligence',
    description: 'Explore the latest trends and breakthroughs shaping the AI landscape in 2026.',
    image: blogGoldImage,
    date: '01 Apr 2026',
    readingTime: 6,
    publishedDate: '18 Apr 2026',
  },
  {
    id: 6,
    status: BlogStatus.PUBLISHED,
    title: 'How to Build a Successful Tech Career',
    description: 'Insights from senior engineers on growing from junior to principal level.',
    image: blogGoldImage,
    date: '28 Mar 2026',
    readingTime: 8,
    publishedDate: '27 Mar 2026',
  },
];
